### ISSUE TITLE
Image quality is slightly degraded

### ISSUE THREAD

**Issue by daithimorton** [kangabru/pretty-snap#1] opened 2020-12-09 16:46 UTC
Hey! I really like this tool well done!

I'm noticing that there is a slight decrease in the quality of the image afterward. 

Original
![Screenshot 2020-12-09 at 16 22 58](https://user-images.githubusercontent.com/3397660/101659277-cce66780-3a3d-11eb-9a32-57acf0d1bae0.png)

After adding background and downloading the new image
![7ec98e54-f86b-4f08-9540-22d36702b918_2](https://user-images.githubusercontent.com/3397660/101659334-da035680-3a3d-11eb-8650-9d3a856beda7.png)

It may not be noticeable at first glance but I was using your tools image in a package README on NPM and the text was slightly blurred. I've since just overlapped my original image with this new one to get the quality + have the background. 

Is there a way to keep the original image quality and have the border? Or could it be NPM compressing the image before publishing I wonder 🤔

**Comment by kangabru** [comment] 2020-12-10 03:09
Hey daithimorton!

Yeah that's annoying. I just had a quick test to compare the original and pretty snap versions and it seems there's no quality loss on my end using Firefox. There's a slight colour change but that's the only difference I can see. Here's an after/before comparison of my quick test:

![image](https://user-images.githubusercontent.com/55638818/101708224-6e77b400-3a52-11eb-87c5-ddbfedc1099b.png)

I also tried to the design the export process to maintain quality as follows:
- It exports a png which is a lossless quality format
- It renders the image at the original size so scaling doesn't impact anything

I also looked into the image on npm and found the following:
- npm is using the Github hosted image directly
- The image is a png so image compression isn't likely the problem

Based on my test and looking into the image I suspect that the issue is simply the small resolution of the image (and perhaps the quality of the screenshot tool you're using)

What I suggest you try is to simply take a screenshot of the text but at a larger resolution. That way the text should look sharper when scaled down or even after image compression. In vscode for example you can easily increase the font size or zoom level via the settings. It's not ideal but should be quick to do.

I hope that helps and solves your problem! Let me know if it works. Also if you do find a situation where the quality degrades directly from using pretty snap then definitely let me know.

**Comment by kangabru** [comment] 2020-12-15 00:15
Closing as the issue appears to be unrelated to Pretty Snap itself.

**Closed by kangabru** 2020-12-15 00:15 UTC
